services:
  - type: web
    name: shibangi-portfolio
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn portfolio_project.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
