# Generated by Django 5.2.10 on 2026-07-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_product_category_item_uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='unique_product_category_per_subcategory',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='portfolio_app.category'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='portfolio_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_products/'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('subcategory__isnull', True)), models.Q(('category__isnull', True), ('subcategory__isnull', False)), _connector='OR'), name='product_category_has_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'name'), name='unique_product_category_per_category'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'name'), name='unique_product_category_per_subcategory'),
        ),
    ]
