# Generated by Django 5.2.10 on 2026-07-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_seed_highlight_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(blank=True, max_length=160)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('institution_name', models.CharField(blank=True, max_length=180)),
                ('university_board', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('cgpa_percentage', models.CharField(blank=True, max_length=80, verbose_name='CGPA / Percentage')),
                ('description', models.TextField(blank=True)),
                ('certificate_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=160)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('part_time', 'Part-time')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('work_mode', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=20, verbose_name='Remote / Onsite / Hybrid')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience_logos/')),
                ('company_website', models.URLField(blank=True)),
                ('project_link', models.URLField(blank=True)),
                ('certificate_offer_letter', models.FileField(blank=True, null=True, upload_to='experience_documents/')),
                ('experience_summary', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('technologies_used', models.CharField(blank=True, max_length=240)),
                ('achievements', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date', '-created_at'],
            },
        ),
    ]
