# Generated by Django 5.2.10 on 2026-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0015_seed_resume_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightpost',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='highlight_documents/'),
        ),
        migrations.AddField(
            model_name='highlightpost',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='highlightpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='highlight_images/'),
        ),
    ]
