# Generated by Django 5.2.10 on 2026-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_highlightpost_document_highlightpost_external_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shibangi Khan', max_length=120)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
    ]
