# Generated by Django 5.2.10 on 2026-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_seed_site_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='cv_url',
            field=models.URLField(blank=True, verbose_name='CV / resume link'),
        ),
    ]
